professions:
  weaponsmithing:
    level 1:
      xpneeded: 300
      commands:
        - give @p 1 1
      skills:
      - item you get
    level 2:
      xpneeded: 300
      commands:
        - give @p 1 2
      skills:
      - level 2 item
    level 3:
      xpneeded: 300
      commands:
        - give @p 1 3
      skills:
      - pt2 item you
    level 4:
      xpneeded: 300
      commands:
        - give @p 1 4
      skills:
      - pt2 level 2
  armorsmithing:
    level 1:
      xpneeded: 300
      commands:
        - give @p 2 1
      skills:
      - second prof item you get
    level 2:
      xpneeded: 300
      commands:
        - give @p 2 2
      skills:
      - etc etc